# Generated by Django 4.2.5 on 2023-09-23 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_account_type_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_type',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.account')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.customer')),
            ],
        ),
    ]
