# Generated by Django 4.2.5 on 2023-10-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_loanapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Loan'), ('approved', 'Approved Loan'), ('denied', 'Denied Loan')], default='pending', max_length=10),
        ),
    ]
