# Generated by Django 4.2.5 on 2023-10-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_rename_account_typeid_account_account_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='customerid',
            new_name='customer',
        ),
    ]
