# Generated by Django 4.2.5 on 2024-01-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_rename_customerid_loanapplication_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='supervisor_approval',
            field=models.CharField(choices=[('pending_supervisor', 'Pending Supervisor Approval'), ('approved_supervisor', 'Approved by Supervisor'), ('denied_supervisor', 'Denied by Supervisor')], default='pending supervisor', max_length=20),
        ),
    ]
