# Generated by Django 4.2.5 on 2024-01-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_loanapplication_supervisor_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='supervisor_approval',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='supervisor_approved',
            field=models.BooleanField(default=False),
        ),
    ]
